name: brainfuck
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Rodrigo Muniz <rodrigo.temiski1995@gmail.com>

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  rxdart:

dev_dependencies:
  build_runner:
  build_web_compilers:
  test:
  pedantic:
