name: brainfuck
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Rodrigo Muniz <rtmuniz@positivo.com.br>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  rxdart: ^0.22.0

dev_dependencies:
  build_runner: ^1.6.1
  build_web_compilers: ^2.1.2
  test: ^1.6.5
  pedantic: ^1.0.0
